### ISSUE TITLE
Error on console: TypeError: Object.isObject is not a function

### ISSUE THREAD

**Issue by heavybeard** [getninjaN/angular-sticky-kit#1]
Hi @getninjaN,
thanks for migrating sticky-kit on angular.

I have an error on your code: `customOptions = Object.isObject(stickyKitAttribute) ? stickyKitAttribute : {};`
The Console tell me that the isObject funtion does not exist

Here is some screeshot
![image](https://cloud.githubusercontent.com/assets/12038447/16263726/2303d518-3876-11e6-9041-f2cd4b9021bf.png)

![image](https://cloud.githubusercontent.com/assets/12038447/16263743/2af70862-3876-11e6-89f9-e94b432e4bb1.png)

![image](https://cloud.githubusercontent.com/assets/12038447/16263753/3f53de02-3876-11e6-88ca-a28c259f9e0e.png)

**Comment by getninjaN** [comment]
Hi @heavybeard,
and thank you! :)

I think that the `Object.isObject` is part of SugarJS and I forgot to change it to a native JavaScript-check.
The correct check should probably be
`customOptions = typeof stickyKitAttributes == 'object' ? stickyKitAttribute : {};`.

Will fix this as soon as I get the time or if you feel like it try it out and create a Pull request. :)

Cheers,
getninjaN

**Comment by heavybeard** [comment]
An other error is on Object.merge
I have fix it and I open a new Pull Request here https://github.com/getninjaN/angular-sticky-kit/pull/2

**Comment by getninjaN** [comment]
Excellent!
Thank you.
