### ISSUE TITLE
Question: How attach events sticky_kit:*

### ISSUE THREAD

**Issue by heavybeard** [getninjaN/angular-sticky-kit#3]
Sorry for this question, but I tried to attach the event sticky_kit:stick but without results.
Did you try it?
If yes, can you explain how? (in short words if you have no time)

Thanks

**Comment by getninjaN** [comment]
Hi!
Sorry for the late reply. I'll take a look at this as soon as possible.
My guess is that there are some missing `$scope.$apply`, or something like that.

But I'll take a look.

Thanks for helping out,
// getninjaN

**Comment by heavybeard** [comment]
No problem! Now I adopted a work around with window.resize event.

I await news
