### ISSUE TITLE
stick mutpliple divs in wrapper

### ISSUE THREAD

**Issue by r2get** [getninjaN/angular-sticky-kit#4]
Hi, im trying to stick a right and a left bar. But for some reason only 1 sticks. not both: see: http://stackoverflow.com/questions/38439085/sticky-kit-angular-directive-use-on-multiple-columns-does-not-work-only-1-bar-g

**Comment by getninjaN** [comment]
Hi, sorry for the late reply.
I have no problem sticking multiple elements on a page, as seen here: https://plnkr.co/edit/lgZTzcveDYkf5jCqOgC5

Could you create a Plunker with your example?

Cheers,

getninjaN

**Comment by getninjaN** [comment]
I take it this has been resolved. Feel free to open the issue again if this is not the case.
